### ISSUE TITLE
suggestion: `Entity:restrict` method

### ISSUE THREAD

**Issue by HDictus** [Tjakka5/Concord#42]
The Problem:

When using components for status effects, it makes sense to remove the components related to actions which that status prevents. One problem that arises with this is with two status effects that have an action that they both restrict.
 For example, you have a 'stunned' status effect which prevents both movement and attacking:
```
function StunSystem:stun(entity, duration)
    entity:give('stunned', duration)
    entity:remove('canattack')
    entity:remove('canmove')
end

function StunSystem:end_stun(entity)
    entity:remove('stunned')
    entity:give('canattack')
    entity:give('canmove')
end
```

and a 'rooted' status, which only prevents movement

```
function RootSystem:root(entity, duration)
   entity:give('rooted', duration)
   entity:remove('canmove')
end

function RootSystem:end_root(entity, duration)
   entity:remove('rooted')
   entity:give('canmove')
end
```

The problem that arises is that if an entity is rooted for a long time, while also being stunned for a short time they will wind up moving as soon as their stun ends even if they are still supposedly rooted. One very poor solution would be to have every status effect check all overlapping ones and only give the components when appropriate - obviously not a favorable approach. Another would be to have the actions (MovementSystem, AttackSystem) check what status effects are active instead of including 'canmove' and 'canattack' in the pool. Besides being inefficient, that approach also seems to me to be poor separation of concerns. The effects of a particular status effect should be contained within the system that implements it.

The proposed solution: : `Entity:restrict(component)` and `Entity:unrestrict(component)`

`Entity:restrict` will record that something is preventing the passed component from being active and will 'hide' it so that the entity is excluded from pools containing that, and it maintains a counter of the number of times the component is restricted.

`Entity.unrestrict' will decrement the aforementioned counter, and if it reaches 0 (indicating that nothing is now restricting the component) it will un-hide the the component in question.

Another advantage of this is that it allows one to temporarily remove parameterized components and add them with the same values as before without caching them (as `:remove` would handle that).

Let me know what you think. I'll be doing something like this for a project anyway so I can easily make a PR afterward with my modification.

**Comment by pablomayobre** [comment]
I think your issue can be fixed with Component Negation (see #32) which would allow you to specify that you only want entities that `canmove` but are not `stunned` nor `rooted` so you could specify your filters such as:

```lua
local YourSystem = Concord.system({
   movable = { "canmove", "!stunned", "!rooted" },
   attacker = { "canattack", "!stunned" }
})
```

And now you don't need to remove `canattack` and/or `canmove` whenever you give these status effects.

This aligns with your second proposed solution:
> Another would be to have the actions (MovementSystem, AttackSystem) check what status effects are active instead of including 'canmove' and 'canattack' in the pool. Besides being inefficient, that approach also seems to me to be poor separation of concerns. The effects of a particular status effect should be contained within the system that implements it.

Don't worry this is not inefficient, component negation is just as fast and simple any other Filter check. You also mention that it's a poor separation of concepts, but to be fair these components are flag that tell your system whether this Entity can perform the action the System takes care of.

All in all, it's a little more redundant than adding and removing a single `canmove` flag, but it's a great solution for your specific use case.

------

Your proposed solution sounds useful but it's still added complexity to Concord (which tries to be minimal but feature complete). 

You also need to take into account you will need to have a separate location for restricted components, and possibly needing an `isRestricted` check. Then again it's doable, and if you want to make a PR so we can better evaluate how useful it is and what problems may arise later, I'll definitely appreciate it.

**Comment by HDictus** [comment]
Thanks for taking the time to reply! 
Ah, I didn't know about component negation! That's a much better solution. I think you're right as well that as long as it's in the pool declaration the concern is exactly where it should be. This was really helpful, thanks!

**Comment by HDictus** [comment]
I don't have other usecases in mind for this so as you say it wouldn't be worth the complexity. As far as I'm concerned this issue can be closed.

**Comment by pablomayobre** [comment]
Great to hear!

I'm glad that this can be solved with "Component Negation" since I feel it's the ideal use case for this feature.

I will keep this in the back of my mind just in case it's needed at some point 💖 

Thank you very much for your proposal, really appreciated.
