### ISSUE TITLE
No way of removing a system

### ISSUE THREAD

**Issue by chicogamedev** [Tjakka5/Concord#43]
Hi, 

I'm starting to work on a project using Concord and everything seems really fine to me.

But I think I'm missing something. Should I add all the systems to the world at the beginning and do not care about which one are used or not in the current context ?

I mean, there is no way of cleaning the world of unused systems. 

For exemple, my main menu will use systems that will have absolutely no use in the game state. Should I just disable it ? 

Sorry if this is a dump question and thanks in advance for the answer.

Thanks for the great work 👍

**Comment by pablomayobre** [comment]
If those Systems share Entities then yes, the recommended way is enabling/disabling as needed.

However, if the System's don't affect the same set of Entities, as may be the case with a menu and the main game, you can use two separate Worlds to handle each of the game states.

---

Enabling and disabling is cheaper than adding an removing, since it guarantees that the Pools are always up to date, instead of having to loop through all Entities every single time the system is added.

**Comment by chicogamedev** [comment]
Ah yes I have not thought about the multiples worlds, thats an amazing idea.

But how to dispose a world ? Wait for the garbage collector ?


Thanks

**Comment by pablomayobre** [comment]
Yeah dereferencing is the easiest way to clean up a World. It's a table after all, so there is no easy way to clean it otherwise.

You can clear all the Entities in a World if needed but that only destroys those Entities (dereferences actually, so the GC can pick them up), doesn't destroy the System instances nor the World itself.
